---
title: "Timeline-Vis"
author: "Ian Sims"
date: "February 20, 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(DiagrammeR)

m = mermaid("
    gantt
    dateFormat  YYYY-MM-DD
    title A Very Nice Gantt Diagram
    
    section Basic Tasks
    This is completed             :done,          first_1,    2014-01-06, 2014-01-08
    This is active                :active,        first_2,    2014-01-09, 3d
    Do this later                 :               first_3,    after first_2, 5d
    Do this after that            :               first_4,    after first_3, 5d
    
    section Important Things
    Completed, critical task      :crit, done,    import_1,   2014-01-06,24h
    Also done, also critical      :crit, done,    import_2,   after import_1, 2d
    Doing this important task now :crit, active,  import_3,   after import_2, 3d
    Next critical task            :crit,          import_4,   after import_3, 5d
    
    section The Extras
    First extras                  :active,        extras_1,   after import_4,  3d
    Second helping                :               extras_2,   after extras_1, 20h
    More of the extras            :               extras_3,   after extras_1, 48h
    ")

m$x$config = list(ganttConfig = list(
  axisFormatter = list(list(
    "%b %d, %Y"
    ,htmlwidgets::JS(
      'function(d){ return d.getDay() != 8 }'
    )
  ))
))


m

```

```{r}
library(DiagrammeR)
library(tidyr)
library(dplyr)

df <- data.frame(task = c("task1", "task2", "task3"),
                 status = c("done", "active", "crit"),
                 pos = c("first_1", "first_2", "first_3"),
                 start = c("2014-01-06", "2014-01-09", "2014-01-09"),
                 end = c("2014-02-06", "60d", "365d"))

m = mermaid(
      paste0(
        # mermaid "header", each component separated with "\n" (line break)
        "gantt", "\n", 
        "dateFormat  YYYY-MM-DD", "\n",
        "title A Very Nice Gantt Diagram", "\n",
        # unite the first two columns (task & status) and separate them with ":"
        # then, unite the other columns and separate them with ","
        # this will create the required mermaid "body"
        paste(df %>%
                unite(i, task, status, sep = ":") %>%
                unite(j, i, pos, start, end, sep = ",") %>%
                .$j, 
              collapse = "\n"
        ), "\n"
      )
    )

m$x$config = list(ganttConfig = list(
  axisFormatter = list(list(
    "%b %y"
    ,htmlwidgets::JS(
      'function(d){ return d.getDay() != 8 }'
    )
  ))
))


m

```

```{r echo = FALSE}
library(timevis)

dataGroups <- read.csv(header = TRUE, text = "
id,content,group,start,end,style
1,Task 1,Common,2016-12-02,2017-03-17,NA
2,Task 2,Common,2016-12-02,2017-02-17,background-color: red;color: white
3,Task 3,Common,2016-12-02,2017-03-17,NA
4,Task 4,Section 1,2016-12-02,2017-02-17,background-color: red
5,Task 5,Section 1,2017-03-17,2017-04-07,NA,NA
6,Task 6,Section 2,2017-03-17,2017-04-27,NA,NA
7,Task 7,Section 2,2017-04-07,2017-04-27,NA,NA
8,Task 8,Section 2,2017-05-07,2017-05-17,background-color: red
9,Task 9,Section 2,2017-06-07,2017-06-20,NA,NA
10,Task 10,Section 3,2017-07-07,2017-07-31,background-color: red
")

groups <- read.delim(header = TRUE, sep = ":", text = "
id: content
Common:Common
Section 1:Section 1
Section 2:Section 2
Section 3:Section 3
")
  
timevis(
  dataGroups,
  groups, 
  showZoom = TRUE,
  zoomFactor = 1,
  fit = TRUE
)
```
